### PR TITLE
i3bar icons

### PR DESCRIPTION
**Pull request by akolosov**
xbm icons in i3bar. Like this:

```
{"icon": "/pathtoicons/mem.xbm", "full_text": " $memperc%", ${if_match ${memperc} > 70} "icon_color": "\#FB4646" ${else} "icon_color": "\#F3D194" ${endif}},
{"icon": "/pathtoicons/cpu.xbm", "full_text": " $cpu%", ${if_match ${cpu} > 60} "icon_color": "\#FB4646" ${else} "icon_color": "\#94D1F3" ${endif}},
{"icon": "/pathtoicons/temp.xbm", "full_text": " ${acpitemp}°", ${if_match ${acpitemp} > 60} "icon_color": "\#FB4646" ${else} "icon_color": "\#94F394" ${endif}},
{"icon": "/pathtoicons/clock.xbm", "full_text": " ${time %H:%M:%S}", "icon_color": "\#34E484" }
```

### CODE REVIEW

**Comment by Airblader** [comment]
Well, as it stands it's not mergable because it breaks several things, including i3 default behavior and some of my own fixes (both new features and fixes for i3). I'll have a look at this sometime to see if I can fix it easily.

If you use my fork with this patch you should be aware that the `height` directive in the bar config will not work correctly and that setting background and border colors probably appear buggy.

**Comment by akolosov** [comment]
ok

**Comment by Airblader** [comment]
I've opened #28 to track this in the issues.

**Comment by Airblader** [comment]
Thinking about it a little, I think I don't want to merge this. It's maintenance effort that I think is unnecessary with the use of iconic fonts.

See https://wiki.archlinux.org/index.php/i3#Iconic_fonts_in_the_status_bar

**Pull request closed without merging**
