### PR TITLE
add AUR package

### PR DESCRIPTION
**Pull request by bandali**
I thought it'd be nice to have an AUR package for this, so I submitted one today.

### CODE REVIEW

**Comment by Airblader** [comment]
This is neat, thanks!

How does this work with the AUR? How did you build the package? Does it have to be updated manually or can it automatically pull from git through the magic powers of Arch? Is there any way to add me as another maintainer?

**Comment by bandali** [comment]
No problems :)
1. To install AUR packages, you either download the tarball and build it yourself, or use an AUR helper (e.g. yaourt,...)
2. AUR packages aren't _built_. They describe how to be built, the user builds the package themselves (again, manually or using an AUR helper).
3. I think you'd have to update manually, just like all other packages: either use `yaourt -Syua` or be specific: `yaourt -S i3-gaps`. It's a git package, so I guess yes it will always pull the latest release. Due to that, I'm not sure if I should have named the package as `-git` or not. Non-VCS packages are expected to be manually updated for each release, and some AUR helpers rely on the `-git` suffix to update git packages (as the package will likely not change in a long while due to it always downloading the latest from github).
4. Yes. I have to orphan the package first, then you can take back ownership of it.﻿

3rd and 4th answers by Maxime Poulin ([here](https://plus.google.com/100238012174176423914/posts/68BaaWst2MC))

**Comment by maxpoulin64** [comment]
To add to @aminb first two points, AUR packages are pretty much nothing more than fancy bash scripts that tells how to compile the program from source. They don't contain the program itself. Users download the PKGBUILD file and use Arch's `makepkg` command over it, and it automagically downloads the sources for the program, its dependencies if needed and build it. All the needed information is available [here, on the ArchLinux's Wiki](https://wiki.archlinux.org/index.php/AUR). Since it's just a build script, it can be made to always pull the latest version, or to always download a specific tag or commit, or a .zip on the Internet.

The source code for the PKGBUILD [can be found here](https://aur.archlinux.org/packages/i3/i3-gaps/PKGBUILD). Just a bunch of variables, the `build()` function which just runs `make`, and the `package()` function which just runs `make install` and copies a few other files.

@Airblader If you are not an ArchLinux user, I would strongly recommend to leave the package maintenance to @aminb in order to maintain the package up to Arch's packaging standards. The AUR already includes a way for users to flag it as outdated (needs to be updated), as well as a comment section for Arch users to report bugs related to the _packaging_ of the software. As the upstream developer, this shouldn't add you any more work (it would be unreasonable anyway for you to have to support all the distros in existance). The AUR link is just a convenience for users to know right away it's available for their distro and that they don't need to manually download the required libraries, convert the Debian package names (from your `apt-get install` command) to Arch's naming and manually build it. They can just use their favorite AUR helper and have it installed automatically like if it was in the regular repos.

**Comment by Airblader** [comment]
Thanks, guys.

@maxpoulin64 I only asked for maintenance rights, not ownership. I'm totally cool with not having ownership. But if the package automatically pulls the latest git commit anyway, I won't have a reason to do something (I only asked so I'd be able to keep it up to date in case it had to be done manually). I'd be okay even without it, I just figured asking won't hurt. :)

I'm not an Arch user yet, but I'm preparing to switch to Manjaro at some point, so at that point in time I could've maintained it more easily. But I'm unsure when this will happen and again, it doesn't seem to be necessary anyway.

Give me some time to just look at this a little, then I'll merge it. Thanks for the contrib!

**Comment by Airblader** [comment]
@aminb Would it be possible to change the AUR package to use the `gaps` branch rather than `gaps-next`? It's not the active i3 development version, but my active development version. Maybe add a second `i3-gaps-next` package? Or are there any issues with this regarding the Arch philosophy?

**Comment by bandali** [comment]
Thanks for merging. I'll most likely have to re-submit the package since I didn't use the `-git` suffix. I can submit two packages: `i3-gaps-git` and `i3-gaps-next-git`. How does that sound?

BTW, I didn't fully understand your explanation about the branches. So, `gaps` is your active development version?

**Comment by Airblader** [comment]
Yes, I develop on `gaps` which is synchronized with `i3/master` (i3-stable). But I, of course, merge everything into `gaps-next` which is synchronized with `i3/next`. Basically, I want to be able to provide i3-stable with my changes which makes it easier to decide whether a bug is "mine" or caused by i3's active development (and, in fact, I personally use `gaps` and not `gaps-next`).

Sorry you have to resubmit the packages; I hope it's not too much trouble. But it'd probably be cleaner that way. Will you submit another PR for the changes to the README.md?

**Comment by bandali** [comment]
Oh I see. That makes sense.

No worries, it'll hopefully be better that way; and it shouldn't be much trouble. And yes I'll open another PR after submitting the 2 new packages.

**Pull request merged**
