### PR TITLE
update AUR links

### PR DESCRIPTION
**Pull request by bandali**
As mentioned in #19, I added two new AUR packages `i3-gaps-git` and `i3-gaps-next-git`.

Moreover, I've filed a merge request and the current `i3-gaps` package's comments and votes will be soon merged into `i3-gaps-git`.

### CODE REVIEW

**Comment by Airblader** [comment]
Awesome. Thanks for the contribution, it is very much appreciated!

**Comment by bandali** [comment]
No problems man. BTW, do you have any plans on merging from the original i3 code base?

**Comment by Airblader** [comment]
I look frequently and can hopefully keep merging regularly. In fact, I tried merging much more often than there are changes. My plan is definitely to stay up to date with vanilla i3. :) As long as there are no major refactorings it should be fine (hopefully)

**Comment by bandali** [comment]
Oh I see. Thanks :) So, that means you have version 4.8 merged as well?

**Comment by Airblader** [comment]
Yes. I merge `i3/master` into `gaps` and `i3/next` into `gaps-next` regularly. :)

**Comment by bandali** [comment]
Oh OK thank you. I asked because on the 'release' page of this repo, the newest tag is 4.7.2 but in the i3wm code base the newest tag is 4.8. Maybe you could merge the tags as well (if that makes sense)?

**Comment by Airblader** [comment]
I'm not too sure about merging tags. I certainly won't add my own and would assume that someone using my fork will just check out the latest commit of either branch. I see how it is confusing, though. I should probably remove the tags.

**Comment by Airblader** [comment]
All tags are gone now.

**Comment by bandali** [comment]
Thanks again :]

**Comment by Airblader** [comment]
Change of plans. I merged all upstream tags and pushed them again since this caused #26. I'd still not recommend using them, though, but this is less effort for a non-problem.

**Comment by Airblader** [comment]
@aminb I'm using Manjaro as one of my main systems now, so I'm fairly active using the AUR. As said before, you made the packages and you can, of course, keep that, but if possible I'd like to be a maintainer just in case something changes. My username is Airblader. Thanks :)

**Comment by bandali** [comment]
@Airblader Great news! Welcome to the community of Archer's (sort of :stuck_out_tongue:).

Sure, I orphaned both of the packages, feel free to adopt them.

I'm not sure how familiar you are with the AUR, but in the case of these packages, since they are `-git` packages, you don't have to update them everytime you push to github. It'd be nice to do so whenever there's a release (git tag) so that the major and minor version of the aur package would match the latest release.

**Comment by Airblader** [comment]
Thanks! I thought it'd be possible to have multiple maintainers; I didn't mean to push you off of the package — sorry! I think it's better this way though, since I'm watching i3 more closely (probably, at least). 

I knew I didn't have to update the git package, but thanks for hinting me to update the version numbers. I'm guessing that's also how the client receives the information that there is an update?

**Comment by bandali** [comment]
No problems. No, that's OK it's probably better this since you're the dev and also as you said, you follow i3 more closely than I do.

Yeah that's good to know. I'm pretty sure this is the case for `yaourt`, but I can't say for other AUR helpers (like `pacaur` or `aura`) since I haven't used them much.

Basically, AFAIK, with `-git` packages whenever you do a `yaourt -S packagename` it pulls from the git repo, so it always gets the latest; but `yaourt -Syua` wouldn't know it has to update because the package version hasn't changed. So, whenever you want to make sure that your changes are seen as an update to existing installations, you have to upload a new package file so that the AUR version is updated.

**Comment by Airblader** [comment]
Yeah, that's what I figured. Thanks! I guess it's a balance between offering bleeding edge and spamming updates (since at least with yaourt, the entire git repo will be cloned every time).

One question, though. Why does the PKGBUILD copy all binaries manually? Why not just run `make install` outside fakeroot? Is this simply considered good practice or is there any other reason for it?

Also, after reading the arch wiki articles on this: for all I can tell, I can simply take the current PKGBUILD, update it, run `makepkg --source` and upload that tarball? The arch wiki lists `namcap` for sanity checking, which seems to fail if I do that (it says it's not a valid package – but also on the tarball currently in the AUR)

**Comment by bandali** [comment]
> Yeah, that's what I figured. Thanks! I guess it's a balance between offering bleeding edge and spamming updates (since at least with yaourt, the entire git repo will be cloned every time).

No worries, yeah that's true :)

> One question, though. Why does the PKGBUILD copy all binaries manually? Why not just run make install outside fakeroot? Is this simply considered good practice or is there any other reason for it?
> Also, after reading the arch wiki articles on this: for all I can tell, I can simply take the current PKGBUILD, update it, run makepkg --source and upload that tarball? The arch wiki lists namcap for sanity checking, which seems to fail if I do that (it says it's not a valid package – but also on the tarball currently in the AUR)

To be completely honest, I'm not much of an AUR power user or packager, I mostly use it just for installing packages. As I mentioned in the PKGBUIDs, `# This PKGBUILD was based on that of i3-git, prepared for pacman 4.1 by William. Modifications by Amin Bandali`.

I can do some PKGBUILD modifications, as much as my knowledge allows me, but that's it. I haven't taken time to read through all the wiki pages about AUR and its toolings. Maybe @maxpoulin64 could help us here ?

**Comment by maxpoulin64** [comment]
@aminb It depends on a few things. @Airblader is partly right: `make install` would be cleaner, but there are slight modifications that needs to be done:

Taken from a random package [xfce4-panel](https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/xfce4-panel), the code would look like this:

``` bash
build() {
  cd "$srcdir/$pkgname-$pkgver"

  ./configure --prefix=/usr
  # ...
  make
}

package() {
  cd "$srcdir/$pkgname-$pkgver"
  make DESTDIR="$pkgdir" install
}
```

Notice the `DESTDIR="$pkgdir"` in the package() function. I don't know if this is a standard variable, but that's how most of the packages do it. Maybe the maintainer of the [original i3-wm package](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/i3-wm) did that because it didn't work properly, but I have no idea as I don't use i3 nor have any knowledge on it.

@Airblader Running make outside of fakeroot is impossible. We need the package to output to the proper directory one way or another.

**Comment by Airblader** [comment]
Thanks, guys! The i3 package also does `make DESTIDR="$pkgdir/" install'; the manually copied files are the`man` files. I just tried it and they don't seem to be generated by the make process, so I guess that's the reason.

I'll update the PKGBUILDs sometime soon. I appreciate your help!

**Comment by bandali** [comment]
@Airblader No worries, I didn't do much though, I'm glad @maxpoulin64 could help.

@maxpoulin64 Thanks for the detailed explanations man!

**Pull request merged**
